name: "📦 请求添加新项目"
description: "想向 bytes 中添加某个项目吗？"
title: "新增项目："
labels: ["add-project"]
body:
  - type: markdown
    attributes:
      value: |
        请确保这一项目尚未被收录，而且还没有其他人请求。

        （已收录的项目在 [projects.yaml](https://github.com/YDX-2147483647/best-of-bits/blob/main/projects.yaml)、[README.md](https://github.com/YDX-2147483647/best-of-bits/blob/main/README.md) 两个文件，其他人的请求在[议题](https://github.com/YDX-2147483647/best-of-bits/issues?q=is%3Aopen+label%3Aadd-project)）

  - type: markdown
    attributes:
      value: |
        ### 项目细节

        请尽可能填写下列信息，不过填不全也没关系。

  - type: input
    id: name
    attributes:
      label: 名称
    validations:
      required: true
  - type: input
    id: github
    attributes:
      label: GitHub URL
  - type: dropdown
    id: category
    attributes:
      label: 类别
      description: 从已有类别中选，参考`README.md`或`projects.yaml`里的`categories`
      options:
        # sync-categories: start
        - 📁模板
        - 📥汇总或重定向信息
        - 🔑认证校园网
        - 📡学校网站与网络
        - 👩‍🏫教学运行与考务
        - 📅管理时空流形
        - 📚学习资料
        - 🧪实验／实践
        - 🧑‍🤝‍🧑存在一定结构的人的集合
        - 👩‍🚀First BIT for Mankind
        - 🐱‍🐉杂项
        # sync-categories: end
  - type: input
    id: license
    attributes:
      label: 许可证
      placeholder: MIT
  - type: textarea
    id: package
    attributes:
      label: 包管理器
      description: |
        填写各种包管理器收录的 ID，包管理器如 npm、pypi、conda、dockerhub、maven、apt……
      placeholder: |
        pypi: tensorflow
        conda: conda-forge/tensorflow
        dockerhub: tensorflow/tensorflow

  - type: markdown
    attributes:
      value: |
        ### 补充

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 如有其它相关信息，可在这里注明。
      placeholder: （可选）